ConsoleUI: update dockerfile to be inline with offical nextjs

diff --git a/console_ui/Dockerfile b/console_ui/Dockerfile
--- a/console_ui/Dockerfile
+++ b/console_ui/Dockerfile
@@ -1,37 +1,46 @@
-# Dockerfile based on example in blog:
-# https://medium.com/@2018.itsuki/dockerize-a-next-js-app-4b03021e084d
-FROM node:18-alpine as base
-RUN apk add --no-cache g++ make py3-pip libc6-compat
-WORKDIR /app
-COPY package*.json ./
-EXPOSE 3000
+# Taken from refine examples
+# https://github.com/refinedev/dockerfiles/blob/main/nextjs/Dockerfile
+# requires output standalone
+FROM refinedev/node:18 AS base
 
-FROM base as builder
-WORKDIR /app
+FROM base AS deps
+
+RUN apk add --no-cache libc6-compat
+
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM base AS builder
+
+COPY --from=deps /app/refine/node_modules ./node_modules
+
 COPY . .
+
 RUN npm run build
 
+FROM base AS runner
 
-FROM base as production
-WORKDIR /app
+ENV NODE_ENV production
 
-ENV NODE_ENV=production
-RUN npm ci
+COPY --from=builder /app/refine/public ./public
 
-RUN addgroup -g 1001 -S nodejs
-RUN adduser -S nextjs -u 1001
-USER nextjs
+RUN mkdir .next
+RUN chown refine:nodejs .next
 
+COPY --from=builder --chown=refine:nodejs /app/refine/.next/standalone ./
+COPY --from=builder --chown=refine:nodejs /app/refine/.next/static ./.next/static
 
-COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
-COPY --from=builder /app/node_modules ./node_modules
-COPY --from=builder /app/package.json ./package.json
-COPY --from=builder /app/public ./public
+USER refine
 
-CMD npm start
+EXPOSE 3000
 
-FROM base as dev
-ENV NODE_ENV=development
-RUN npm install
-COPY . .
-CMD npm run dev
+ENV PORT 3000
+ENV HOSTNAME "0.0.0.0"
+
+CMD ["node", "server.js"]
